# Generated by Django 4.2.2 on 2024-06-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_Table',
            new_name='Data',
        ),
    ]
