# Generated by Django 4.2.2 on 2024-06-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_rename_data_table_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='JoSAA_Data',
        ),
    ]
