# Generated by Django 4.2.2 on 2024-06-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_rename_institue_josaa_data_institute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoSAA_Data',
            new_name='data_Table',
        ),
    ]
