# Generated by Django 4.2.2 on 2024-06-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_rename_josaa_data_data_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data_Table',
            new_name='data',
        ),
    ]
